"""refresh_token

Revision ID: 0e42156842f5
Revises: cd811459358f
Create Date: 2024-06-27 11:27:26.325674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e42156842f5'
down_revision: Union[str, None] = 'cd811459358f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_jwt_token', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_jwt_token')
    # ### end Alembic commands ###
