version: '3.7'
services:
  db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - "5433:5433"

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    ports:
      - "8000:8000"

  celery:
    image: booking_celery
    build:
      context: .
    container_name: booking_celery
    command: ["/booking/docker/celery.sh", "celery"]
    depends_on:
      - redis
    env_file:
      - .env-non-dev

  flower:
    image: booking_flower
    build:
      context: .
    container_name: booking_flower
    command: ["/booking/docker/celery.sh", "flower"]
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    ports:
      - "5555:5555"
  
  web:
    image: nginx
    ports:
    - "8080:80"
    env_file:
    - .env-non-dev
    depends_on:
      - redis